name: Bad CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Setup Node
        uses: actions/setup-node@v3
        with:
          node-version: '18'

      - name: Install dependencies
        run: npm install

      - name: Run tests
        run: npm test || true

      - name: Build application
        run: npm run build

      - name: Build Docker image
        run: docker build -t myapp:latest ./ci-cd


      - name: Deploy to production
        env:
          DATABASE_URL: "postgresql://user:MySecretPass123@db.example.com:5432/app"
          API_KEY: "sk-1234567890abcdefghijklmnop"
          AWS_ACCESS_KEY_ID: "AKIA1234567890ABCDEF"
          AWS_SECRET_ACCESS_KEY: "wJalrXUtnFEMI/K7MDENG/bPxRfiCYEXAMPLEKEY"
        run: |
          echo "Deploying..."
          ssh -i ~/.ssh/id_rsa root@production.example.com "cd /app && docker pull myapp:latest && docker-compose up -d"
